#
# This file has been generated by tools/gen-deps.sh
#

src/s6-overlay-suexec/s6-overlay-suexec.o src/s6-overlay-suexec/s6-overlay-suexec.lo: src/s6-overlay-suexec/s6-overlay-suexec.c

s6-overlay-suexec: EXTRA_LIBS := -lexecline -lskarnet ${SPAWN_LIB} ${MAYBEPTHREAD_LIB}
s6-overlay-suexec: src/s6-overlay-suexec/s6-overlay-suexec.o ${LIBNSSS}
